AllCops:
  Exclude:
    - 'torrentify.gemspec'
    - 'vendor/bundle/**/*'
    - 'test/*'
    - 'spec/*'


Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Enabled: false